### ISSUE TITLE
Upgrade to Elm 0.19

### ISSUE THREAD

**Issue by Pilatch** [romstad/elm-chess#2]
Pretty please? :)

**Comment by Pilatch** [comment]
I'm doing it myself! Got some stuff working. Still a bit more to do I think.

https://github.com/Pilatch/elm-chess/tree/upgrade-to-0.19

I'll issue a pull request soon I hope. I don't want to publish a parallel 0.19 module, but If nobody responds, that's an option.

**Comment by Pilatch** [comment]
Pull request https://github.com/romstad/elm-chess/pull/3

**Comment by romstad** [comment]
Thanks, that's awesome!

Sorry for not responding to this earlier. I've been busy, I haven't done any Elm recently, and I thought this library was still too crude and incomplete to be of any use to outsiders. Your interest makes me consider resuming work on the library and perhaps use Elm the next time I need to do some chess front-end work (most of the time, I use ClojureScript).

**Comment by Pilatch** [comment]
No worries. It was my pleasure. This upgrade forced me to learn how to use Elm's new parsing library. I'd never written a parser before.

I was thinking of making a simple online game that focused on blunders for quirky chess puzzles. I don't think I'll have time for that, but if you want any assistance with this library, you can email me at the following address which I'm spacing out to avoid crawlers spamming me:

ethan
at
pilatch
dot
com
